### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by lim-yoona** [cssl-unist/tweezer#10]
Hello! I have been trying to run tweeter recently. But I encountered some problems. **Background: I am currently running on a machine without an SGX environment, so I only want to use SCONE in simulation mode.**
## Description
I found that I can't pull image from `registry.scontain.com:5050/sconecuratedimages/crosscompilers:ubuntu` , which was provided by Dockerfile of tweezer. So I replaced it with `registry.scontain.com/sconecuratedimages/crosscompilers:ubuntu` , then I can pull the `crosscompilers:ubuntu` image successfully. 
But when I was executing `Docker build - t tweeter: 0.0./` , I found an error. 
![image](https://github.com/cssl-unist/tweezer/assets/44336448/15eed9d1-d47b-4d36-9550-8a6341639ea8)
![image](https://github.com/cssl-unist/tweezer/assets/44336448/c7d51c91-3138-403a-818f-8305296eec89)

I don't know how to solve this problem.

**Comment by hyungon-moon** [comment]
I cannot personally check the details, but it seems that the exact version that the cross compiler is built on is changed from the image that we used. Please find where off64_t should have been defined and make some code changes if needed.

**Comment by lim-yoona** [comment]
> I cannot personally check the details, but it seems that the exact version that the cross compiler is built on is changed from the image that we used. Please find where off64_t should have been defined and make some code changes if needed.

Could you tell me the Musl and Scone versions during your experiment?

**Comment by zktsd813** [comment]
We utilized Musl, which the scone container leverages. However, we regret to inform you that we did not record the specific version of scone back then.

Regarding the error you posted, could you please check if libtcmalloc_minimal.a is generated? If it is found, you can safely ignore the compile error.

**Comment by lim-yoona** [comment]
> We utilized Musl, which the scone container leverages. However, we regret to inform you that we did not record the specific version of scone back then.
> 
> Regarding the error you posted, could you please check if libtcmalloc_minimal.a is generated? If it is found, you can safely ignore the compile error.

With the error, I didn't find the generated libtcmalloc_minimal.a. 
I encountered a dilemma. Since the basic image path in the Dockerfile you provided is now invalid, I need to find the scone image myself, which makes it difficult to reproduce your experimental environment. When I use an older scone image, gperftools compiles and tweezer runs in [Simulation Mode](https://sconedocs.github.io/firstcontainer/). But when I run tweezer in [Hardware Mode](https://sconedocs.github.io/hardwaremode/), I get this error:

<img width="760" alt="image" src="https://github.com/cssl-unist/tweezer/assets/44336448/9ad95e1d-ec56-4fed-bee7-2c4bf6ccdc76">

And when I use the newer scone image, the compilation of gperftools will fail.

**Comment by zktsd813** [comment]
Could you check sgx driver is installed?

**Comment by lim-yoona** [comment]
> Could you check sgx driver is installed?

I think my sgx driver is installed because the demo program I wrote myself can run normally in hw mode based on scone.

I'm not sure if it's a problem with different SGX versions. It seems that illegal instructions are generated, but shouldn't SGX2 be compatible with SGX1?

**Comment by zktsd813** [comment]
Could you check /app/untrusted_memory file exists? 
which is generated by generate_tmpfs script

**Comment by lim-yoona** [comment]
> Could you check /app/untrusted_memory file exists? which is generated by generate_tmpfs script

Here is the /app/untrusted_memory file:
<img width="372" alt="image" src="https://github.com/cssl-unist/tweezer/assets/44336448/eabdb0d6-b07f-4605-80c1-b4b2208da2ef">
and the tmpfs:
<img width="334" alt="image" src="https://github.com/cssl-unist/tweezer/assets/44336448/35a7bf10-5009-48f9-8810-af3d6b14e319">

**Comment by lim-yoona** [comment]
> Could you check /app/untrusted_memory file exists? which is generated by generate_tmpfs script

I'm not using the driver you provided：

<img width="663" alt="image" src="https://github.com/cssl-unist/tweezer/assets/44336448/17b4d8ca-f356-4df5-b4bd-94b8acb79e7e">

will this have an impact？

**Comment by zktsd813** [comment]
> > Could you check /app/untrusted_memory file exists? which is generated by generate_tmpfs script
> 
> I'm not using the driver you provided：
> 
> <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/44336448/295155709-17b4d8ca-f356-4df5-b4bd-94b8acb79e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTc2ODEsIm5iZiI6MTcwNDc5NzM4MSwicGF0aCI6Ii80NDMzNjQ0OC8yOTUxNTU3MDktMTdiNGQ4Y2EtZjM1Ni00ZGY1LWI0YmQtOTRiOGFjYjc5ZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODk0MmE3Y2I4ODQzNGEwNmMyOTI1OWFhYmUzZTYyYzQ3NmI0M2JhYTY2NTUxMzg0YWM0NmE0NmJkZTU0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mU32YC8p23Ku3NGmbZ0R88y2h3l29P9-9gtLnyPAnT4">
> will this have an impact？

I believe other SGX drivers might also work. Isn't 'libtcmalloc_minimal.a' located in the libs folder?

**Comment by lim-yoona** [comment]
> > > Could you check /app/untrusted_memory file exists? which is generated by generate_tmpfs script
> > 
> > 
> > I'm not using the driver you provided：
> > <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/44336448/295155709-17b4d8ca-f356-4df5-b4bd-94b8acb79e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTc2ODEsIm5iZiI6MTcwNDc5NzM4MSwicGF0aCI6Ii80NDMzNjQ0OC8yOTUxNTU3MDktMTdiNGQ4Y2EtZjM1Ni00ZGY1LWI0YmQtOTRiOGFjYjc5ZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODk0MmE3Y2I4ODQzNGEwNmMyOTI1OWFhYmUzZTYyYzQ3NmI0M2JhYTY2NTUxMzg0YWM0NmE0NmJkZTU0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mU32YC8p23Ku3NGmbZ0R88y2h3l29P9-9gtLnyPAnT4">
> > will this have an impact？
> 
> I believe other SGX drivers might also work. Isn't 'libtcmalloc_minimal.a' located in the libs folder?

'libtcmalloc_minimal.a' located in the libs folder：
<img width="438" alt="image" src="https://github.com/cssl-unist/tweezer/assets/44336448/a51ba247-41d1-477b-a4f2-6cac2b07315b">
