### ISSUE TITLE
How to evaluate the range query performance of tweezer

### ISSUE THREAD

**Issue by lim-yoona** [cssl-unist/tweezer#11]
Hi! I am trying to evaluate the range query performance of tweezer. 

In paper, you said that using **seekrandom** benchmark, but I don't know how to config the length of range query and the config.csv seems not contain the range query test.

**Comment by hyungon-moon** [comment]
Is it solved? One of the author is going to check the configuration.

**Comment by lim-yoona** [comment]
> Is it solved? One of the author is going to check the configuration.

I find that **`seekrandom`** with `-seek_nexts` arg can test range query, but I haven't test it.

**Comment by zktsd813** [comment]
> > Is it solved? One of the author is going to check the configuration.
> 
> I find that **`seekrandom`** with `-seek_nexts` arg can test range query, but I haven't test it.

Sorry for late response.
Yes. We used -seek_nexts to evaluate range query.
