### ISSUE TITLE
Is there any way to run TWEEZER on SGXv2?

### ISSUE THREAD

**Issue by tino2024world** [cssl-unist/tweezer#12]
Hello,

After building successfully with the OOT SGX drive and SCONE version Ubuntu18.04-scone5.4.0, it meets the error:![image](https://github.com/user-attachments/assets/1742799d-f7ed-4881-bc6d-6c1b5ac820b6)

However, it runs correctly with the same configuration on an SGXv1 machine.

Thanks.

**Comment by hyungon-moon** [comment]
We plan to make Tweezer run on SGXv2 soon, but we currently don't have any experiences on that.

**Comment by tino2024world** [comment]
Get it. Thanks a lot.
