### ISSUE TITLE
Missing ping.txt?

### ISSUE THREAD

**Issue by donporter** [cssl-unist/tweezer#14]
Hi all,

I was trying to run the tests in csv-to-run.py, and got this error:

> Traceback (most recent call last):
>   File "./csv-to-run.py", line 193, in <module>
>     ping()
>   File "./csv-to-run.py", line 139, in ping
>     res = subprocess.run("./ping.txt")
>   File "/usr/lib/python3.7/subprocess.py", line 488, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: './ping.txt': './ping.txt'

I see the code in csv-to-run.py:

`def ping():
    res = subprocess.run("./ping.txt")`

But the repository does not include this file, nor can I find the code to generate it.  I do see that it is in the .gitignore file.

Can you advise what should be here?

Thanks,
Don

**Comment by hyungon-moon** [comment]
Thank you for reporting.

That part is to signal the end of the experiment, and unnecessary to play with Tweezer.
I've just removed the lines using that function just before.
