### ISSUE TITLE
Missing file ping.txt

### ISSUE THREAD

**Issue by shawnk04** [cssl-unist/tweezer#2]
Hi, I've run into an issue while running csv-to-run.py. Line 136 makes a call to run ping.txt. However there is no ping.txt file included in the repo. The .gitignore in /test/ actually has ping.txt listed in it. 

Does ping.txt need to be manually created by the user? Or was ping.txt a file that was accidentally ignored in development? I assume the latter since it needs to be run.

**Comment by hyungon-moon** [comment]
It is our mistake to leave the call there.
It simply calls a local logging script so you should be able to just ignore it by deleting calls to `ping()`
