### ISSUE TITLE
run tweezer on sgx2

### ISSUE THREAD

**Issue by jyizheng** [cssl-unist/tweezer#5]
I am wondering if it is okay to run tweezer on sgx2. I followed the instructions in the readme. But it failed.
Have you tried this before? Does it work?

**Comment by hyungon-moon** [comment]
We have not tested Tweezer on SGX2, so I cannot be helpful to you in this problem.
I recommend you to check if Scone supports SGX2. Tweezer relies on Scone to work with SGX.

**Comment by jyizheng** [comment]
I got an error below when running tweezer on a machine with SGX2 hardware. 
Can I get any information regarding what would possibly cause this error?
Thanks for any of your help. 

![sgx2-tweezer](https://user-images.githubusercontent.com/2645726/206871349-95ab3fe2-68ae-476c-bcf8-fa8705c691d1.png)

**Comment by jyizheng** [comment]
I also used scone-gdb to debug this issue. But I didn't get any useful information. I paste the debug information below 
to see if you have any suggestions. 

-------------------------------------------------------------------------
root@0163d64e115a:/home/betrfs/tweezer/binary# scone-gdb ./tweezer
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Source directories searched: /opt/scone/scone-gdb/gdb-sgxmusl-plugin:$cdir:$cwd
Setting environment variable "LD_PRELOAD" to null value.
Signal        Stop      Print   Pass to program Description
SIGILL        No        Yes     Yes             Illegal instruction
Signal        Stop      Print   Pass to program Description
SIG37         No        Yes     Yes             Real-time event 37
SIG38         No        Yes     Yes             Real-time event 38
Reading symbols from ./tweezer...
[SCONE] Initializing...
(gdb) run
Starting program: /home/betrfs/tweezer/binary/tweezer
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
[SCONE] Enclave application base: 1000010000

[SCONE] Loaded debug symbols

[New Thread 0x7ffff7ff9700 (LWP 52)]
[New Thread 0x7ffff77f8700 (LWP 53)]
[New Thread 0x7ffff2d62700 (LWP 54)]
[New Thread 0x7ffff2561700 (LWP 55)]
[New Thread 0x7ffff1d60700 (LWP 56)]
[New Thread 0x7ffff155f700 (LWP 57)]
[New Thread 0x7ffff0d5e700 (LWP 58)]
[New Thread 0x7ffff055d700 (LWP 59)]
[New Thread 0x7fffefd5c700 (LWP 60)]
[New Thread 0x7fffef55b700 (LWP 61)]
[New Thread 0x7fffef15a700 (LWP 62)]
[New Thread 0x7fffeed59700 (LWP 63)]
[New Thread 0x7fffee958700 (LWP 64)]
[New Thread 0x7fffee557700 (LWP 65)]
[SCONE|WARN] src/enclave/dispatch.c:197:print_version(): Application runs in SGX debug mode.
        Its memory can be read from outside the enclave with a debugger! This is not secure!

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.
[SCONE|ERROR] tools/starter/signal.c:61:die_by_signal(): Enclave terminated due to signal: Illegal instruction

Thread 11 "tweezer" received signal SIGILL, Illegal instruction.
[Thread 0x7fffee557700 (LWP 65) exited]
[Thread 0x7fffee958700 (LWP 64) exited]
[Thread 0x7fffeed59700 (LWP 63) exited]
[Thread 0x7fffef15a700 (LWP 62) exited]
[Thread 0x7fffef55b700 (LWP 61) exited]
[Thread 0x7fffefd5c700 (LWP 60) exited]
[Thread 0x7ffff055d700 (LWP 59) exited]
[Thread 0x7ffff0d5e700 (LWP 58) exited]
[Thread 0x7ffff155f700 (LWP 57) exited]
[Thread 0x7ffff1d60700 (LWP 56) exited]
[Thread 0x7ffff2561700 (LWP 55) exited]
[Thread 0x7ffff2d62700 (LWP 54) exited]
[Thread 0x7ffff77f8700 (LWP 53) exited]
[Thread 0x7ffff7ff9700 (LWP 52) exited]

Program terminated with signal SIGILL, Illegal instruction.
The program no longer exists.

**Comment by hyungon-moon** [comment]
SIGILL is raised when you tried to execute an instruction that a processor does not implement. What I feel like is that, the toolchain you used to build Tweezer (perhaps what we used) emits some instructions that the processor with SGX2 does not implement (which is kinda wired though).

**Comment by lim-yoona** [comment]
> I got an error below when running tweezer on a machine with SGX2 hardware. Can I get any information regarding what would possibly cause this error? Thanks for any of your help.
> 
> ![sgx2-tweezer](https://user-images.githubusercontent.com/2645726/206871349-95ab3fe2-68ae-476c-bcf8-fa8705c691d1.png)

Hi! I have encountered the same error and I am not sure if you have resolved it. If you could provide me with some useful information, I would greatly appreciate it!
