### ISSUE TITLE
tweezer ecalls 

### ISSUE THREAD

**Issue by jyizheng** [cssl-unist/tweezer#7]
I know tweezer is using scone. I do not fully understand how scone works (still digesting the scone paper).
My question is: does tweezer need to issue an ecall for every insertion?

**Comment by hyungon-moon** [comment]
No, it shouldn't need to.

**Comment by jyizheng** [comment]
Why is it so? Do you have any explanation or pointers for me to get a better understanding of this?

**Comment by hyungon-moon** [comment]
That's actually beyond the scope of the issue tracker, but note that a KVS can also be designed to make an ecall for every request, to fetch one, but a better design should use a ring buffer.
