### ISSUE TITLE
The diff compared with the unmodified rocksdb

### ISSUE THREAD

**Issue by jyizheng** [cssl-unist/tweezer#8]
I want to know how much code is changed by TWEEZER on top of the unmodified rocksdb.
I tried to use the utility diff to see the changes, but there are 1,000 files in the diff result, which is very hard to interpret.
Could you please give a list of files or pointers to the code that is relevant to the techniques implemented in TWEEZER?

**Comment by hyungon-moon** [comment]
Sorry. You should figure that out by yourself.

**Comment by jyizheng** [comment]
The link below is the diff I got by comparing tweezer with unmodified rocksdb.

https://github.com/jyizheng/rocksdb-db/pull/1/files

Are all these changes really necessary for TWEEZER?

**Comment by hyungon-moon** [comment]
You seem to have used a wrong baseline to obtain diff.
