### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by debnil** [cssl-unist/tweezer#9]
Hi! I'm trying to build Tweezer on Ubuntu 20.04. I've created public access tokens using the SCONE instructions and logged into Docker.

When I try to build the existing tweezer image, I get this error:
```
Sending build context to Docker daemon  1.933GB
Step 1/13 : FROM registry.scontain.com:5050/sconecuratedimages/crosscompilers:ubuntu
pull access denied for registry.scontain.com:5050/sconecuratedimages/crosscompilers, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
```

Are you still able to pull this SCONE image?

**Comment by hyungon-moon** [comment]
You need to obtain  access to the repository from the Scone project.
The last time we pulled the image from the repository is Dec 2022, and were able the pull the image back then.
